# Generated by Django 5.1.2 on 2024-11-20 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purch_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaddeficitfiles',
            options={'verbose_name': 'Загрузка файла дефицита', 'verbose_name_plural': 'Загрузка файла дефицита'},
        ),
        migrations.AddField(
            model_name='uploaddeficitfiles',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
