# Generated by Django 5.1.2 on 2024-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purch_manager', '0002_alter_uploaddeficitfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaddeficitfiles',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='uploaddeficitfiles',
            name='file',
            field=models.FileField(upload_to='uploads_deficit_files', verbose_name='Название файла'),
        ),
    ]
