# Generated by Django 5.1.2 on 2024-11-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='uploads_deficit_files'),
        ),
    ]
