# Generated by Django 5.1.2 on 2024-11-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_uploadfiles_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
