# Generated by Django 5.1.2 on 2024-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
