# Generated by Django 5.1.2 on 2024-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_uploadfiles_alter_women_content_alter_women_husband_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='post_docs/$Y/%m/%d', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='uploads_model/'),
        ),
    ]
